---
- name: Configure networking
  ansible.builtin.import_playbook: networking.yml
  tags:
    - networking

- name: Configure multimedia
  ansible.builtin.import_playbook: multimedia.yml
  tags:
    - multimedia

- name: Install desktop applications
  ansible.builtin.import_playbook: apps.yml
  tags:
    - apps

- name: Configure desktop fonts
  ansible.builtin.import_playbook: fonts.yml
  tags:
    - fonts

- name: Configure desktop appearance
  ansible.builtin.import_playbook: appearance.yml
  tags:
    - appearance

- name: Configure development Toolbox
  ansible.builtin.import_playbook: dev-env.yml
  tags:
    - dev
