onboarding = false

[theme]
name = "terminal"
auto_switch = false

[ui]
pane_borders = "always"
pane_outer_borders = true
pane_gaps = true

[keys]
previous_tab = "alt+h"
next_tab = "alt+l"
previous_workspace = "alt+k"
next_workspace = "alt+j"
focus_pane_left = "ctrl+shift+h"
focus_pane_down = "ctrl+shift+j"
focus_pane_up = "ctrl+shift+k"
focus_pane_right = "ctrl+shift+l"

[theme.custom]
accent = "#9fcaff"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#282a2e"
selection_bg = "#333539"
surface0 = "#282a2e"
surface1 = "#333539"
surface_dim = "#111417"
overlay0 = "#8c919a"
overlay1 = "#c2c7d0"
text = "#e2e2e7"
subtext0 = "#c2c7d0"
mauve = "#9fcaff"
green = "#9fcaff"
yellow = "#b6c8e1"
red = "#ffb4ab"
blue = "#ecb3f5"
teal = "#b6c8e1"
peach = "#ffdeab"
