onboarding = false

[theme]
name = "terminal"
auto_switch = false

[ui]
pane_borders = "always"
pane_outer_borders = true
pane_gaps = true

[keys]
previous_tab = "alt+h"
next_tab = "alt+l"
previous_workspace = "alt+k"
next_workspace = "alt+j"
focus_pane_left = "ctrl+shift+h"
focus_pane_down = "ctrl+shift+j"
focus_pane_up = "ctrl+shift+k"
focus_pane_right = "ctrl+shift+l"

[theme.custom]
accent = "#f5bc6e"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#2e2923"
selection_bg = "#39342e"
surface0 = "#2e2923"
surface1 = "#39342e"
surface_dim = "#17130d"
overlay0 = "#9c8e7f"
overlay1 = "#d4c4b3"
text = "#ebe1d8"
subtext0 = "#d4c4b3"
mauve = "#f5bc6e"
green = "#f5bc6e"
yellow = "#e0c29c"
red = "#ffb4ab"
blue = "#c2cd7c"
teal = "#e0c29c"
peach = "#ffdeab"
