onboarding = false

[theme]
name = "terminal"
auto_switch = false

[ui]
pane_borders = "always"
pane_outer_borders = true
pane_gaps = true

[keys]
previous_tab = "alt+h"
next_tab = "alt+l"
previous_workspace = "alt+k"
next_workspace = "alt+j"
focus_pane_left = "ctrl+shift+h"
focus_pane_down = "ctrl+shift+j"
focus_pane_up = "ctrl+shift+k"
focus_pane_right = "ctrl+shift+l"

[theme.custom]
accent = "#afc9e6"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#292a2c"
selection_bg = "#343537"
surface0 = "#292a2c"
surface1 = "#343537"
surface_dim = "#121315"
overlay0 = "#8d9197"
overlay1 = "#c3c7cd"
text = "#e3e2e4"
subtext0 = "#c3c7cd"
mauve = "#afc9e6"
green = "#afc9e6"
yellow = "#bec7d4"
red = "#ffb4ab"
blue = "#dcbce0"
teal = "#bec7d4"
peach = "#ffdeab"
